# Generated by Django 5.2.10 on 2026-03-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
